// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tongkangku_be.Data;

#nullable disable

namespace tongkangku_be.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tongkangku_be.Models.CargoType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("cargo_types");
                });

            modelBuilder.Entity("tongkangku_be.Models.ContractCargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CargoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CargoTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FreightRatePerTon")
                        .HasColumnType("numeric");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("ContractId", "CargoTypeId")
                        .IsUnique();

                    b.ToTable("contract_cargos");
                });

            modelBuilder.Entity("tongkangku_be.Models.LaytimeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualDurationHours")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DemurrageAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DemurrageRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DespatchAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DespatchRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LaytimeHours")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetLaytimeAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("SavedHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("laytime_records");
                });

            modelBuilder.Entity("tongkangku_be.Models.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ports");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AgreedBunkerAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgreedHireAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgreedOtherCharges")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgreedRatePerDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AgreedTotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DemurrageRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DespatchRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalSettlementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RentalRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalLaytimeAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RentalRequestId")
                        .IsUnique();

                    b.ToTable("rental_contracts", (string)null);
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalCostItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Bearer")
                        .HasColumnType("integer");

                    b.Property<int>("CostType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RentalRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RentalRequestId");

                    b.ToTable("rental_cost_items");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BunkerAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HireAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OtherCharges")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RatePerDay")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RentalRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RentalRequestId");

                    b.ToTable("rental_offers");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalOperationalCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CostType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CostType")
                        .IsUnique();

                    b.ToTable("rental_operational_costs", (string)null);
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalPricingSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("ContingencyRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LongDurationMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MediumDurationMaxDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MediumDurationMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ShortDurationMaxDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("ShortDurationMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TargetMargin")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("rental_pricing_settings", (string)null);
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseHirePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("CharterType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChartererId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DischargingPortId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DurationMultiplier")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("LoadingPortId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanDay")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalEstimatedPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChartererId");

                    b.HasIndex("DischargingPortId");

                    b.HasIndex("LoadingPortId");

                    b.HasIndex("VesselId");

                    b.ToTable("rental_requests");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalRequestCargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RentalRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("RentalRequestId", "CargoTypeId")
                        .IsUnique();

                    b.ToTable("rental_request_cargos");
                });

            modelBuilder.Entity("tongkangku_be.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("tongkangku_be.Models.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityFeed")
                        .HasColumnType("integer");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DwtCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RatePerDay")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PortId");

                    b.ToTable("vessels");
                });

            modelBuilder.Entity("tongkangku_be.Models.VesselCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("vessel_categories");
                });

            modelBuilder.Entity("tongkangku_be.Models.VesselDocs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocsName")
                        .HasColumnType("text");

                    b.Property<string>("DocsNum")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VesselId");

                    b.ToTable("vessel_docs");
                });

            modelBuilder.Entity("tongkangku_be.Models.ContractCargo", b =>
                {
                    b.HasOne("tongkangku_be.Models.CargoType", "CargoType")
                        .WithMany("ContractCargos")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.RentalContract", "Contract")
                        .WithMany("ContractCargos")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("tongkangku_be.Models.LaytimeRecord", b =>
                {
                    b.HasOne("tongkangku_be.Models.RentalContract", "Contract")
                        .WithMany("LaytimeRecords")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalContract", b =>
                {
                    b.HasOne("tongkangku_be.Models.User", "Owner")
                        .WithMany("OwnerContracts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.RentalRequest", "RentalRequest")
                        .WithOne("RentalContract")
                        .HasForeignKey("tongkangku_be.Models.RentalContract", "RentalRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalCostItem", b =>
                {
                    b.HasOne("tongkangku_be.Models.RentalRequest", "RentalRequest")
                        .WithMany("CostItems")
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalOffer", b =>
                {
                    b.HasOne("tongkangku_be.Models.User", "Owner")
                        .WithMany("OwnerOffers")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.RentalRequest", "RentalRequest")
                        .WithMany("Offers")
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalRequest", b =>
                {
                    b.HasOne("tongkangku_be.Models.User", "Charterer")
                        .WithMany("RentalRequests")
                        .HasForeignKey("ChartererId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.Port", "DischargingPort")
                        .WithMany("DischargingRentalRequests")
                        .HasForeignKey("DischargingPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.Port", "LoadingPort")
                        .WithMany("LoadingRentalRequests")
                        .HasForeignKey("LoadingPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.Vessel", "Vessel")
                        .WithMany("RentalRequests")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charterer");

                    b.Navigation("DischargingPort");

                    b.Navigation("LoadingPort");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalRequestCargo", b =>
                {
                    b.HasOne("tongkangku_be.Models.CargoType", "CargoType")
                        .WithMany("RentalRequestCargos")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.RentalRequest", "RentalRequest")
                        .WithMany("Cargos")
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("tongkangku_be.Models.Vessel", b =>
                {
                    b.HasOne("tongkangku_be.Models.VesselCategory", "Category")
                        .WithMany("Vessels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.User", "Owner")
                        .WithMany("Vessels")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tongkangku_be.Models.Port", "Port")
                        .WithMany("Vessels")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("tongkangku_be.Models.VesselDocs", b =>
                {
                    b.HasOne("tongkangku_be.Models.Vessel", "Vessel")
                        .WithMany("VesselDocs")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("tongkangku_be.Models.CargoType", b =>
                {
                    b.Navigation("ContractCargos");

                    b.Navigation("RentalRequestCargos");
                });

            modelBuilder.Entity("tongkangku_be.Models.Port", b =>
                {
                    b.Navigation("DischargingRentalRequests");

                    b.Navigation("LoadingRentalRequests");

                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalContract", b =>
                {
                    b.Navigation("ContractCargos");

                    b.Navigation("LaytimeRecords");
                });

            modelBuilder.Entity("tongkangku_be.Models.RentalRequest", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("CostItems");

                    b.Navigation("Offers");

                    b.Navigation("RentalContract");
                });

            modelBuilder.Entity("tongkangku_be.Models.User", b =>
                {
                    b.Navigation("OwnerContracts");

                    b.Navigation("OwnerOffers");

                    b.Navigation("RentalRequests");

                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("tongkangku_be.Models.Vessel", b =>
                {
                    b.Navigation("RentalRequests");

                    b.Navigation("VesselDocs");
                });

            modelBuilder.Entity("tongkangku_be.Models.VesselCategory", b =>
                {
                    b.Navigation("Vessels");
                });
#pragma warning restore 612, 618
        }
    }
}
